### PR TITLE
display character form firebase storage

### PR DESCRIPTION
**Pull request by hdome**

### CODE REVIEW

**Comment by hdome** [comment]
[Character](https://trello.com/c/FSibHSR1/12-character)

**Review by Chadyka — APPROVED** [review]
Code works great! #10  will have some merge conflicts with this though. I'd wait until that PR is merged before this one.

**Comment by Chadyka** [comment]
Changes to be done:
- Persmisson denied on firebase storage

**Comment by Chadyka** [comment]
> Changes to be done:
> 
> * Persmisson denied on firebase storage

Firebase Storage rules have been changed to allow for reading data without authenticattion. Thus, this problem no longer persists and the branch can be merged soon.

**Pull request merged**
